development:
  adapter: postgresql
  encoding: unicode
  database: amtrak_messenger_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: amtrak_messenger_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: amtrak_messenger_production
  pool: 5
  username: postgres
  password: postgres
