development:
  adapter: postgresql
  encoding: unicode
  database: unshiftme_development
  pool: 5
  username: unshiftme
  password: secret

test:
  adapter: postgresql
  encoding: unicode
  database: unshiftme_test
  pool: 5
  username: unshiftme
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: unshiftme_production
  pool: 5
  username: unshiftme
  password: secret
